---
title: "Growth curves"
author: "KM"
date: "2025-12-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = F}
library(tidyverse)
library(Rmisc)
library(lme4)
```

```{r, include = F}
# import mock data
mock_n50 <- read_csv2("mock_n50.csv")
mock_n100 <- read_csv2("mock_n100.csv")

# Variables:

# vocab_score - overall vocab - total number of words child produces, range: 0 - 670
# alternatives - overall gram - total score from alternative sentences, measures complexity of child's sentences

# verb_person - child's score on inflection of verbs by persons, range: 0-6
# verb_tense - child's score on inflection of verbs by tense, range: 0-3
# verbs - because the two above have such narrow score ranges, this is a summed verbs score: verb_person + verb_tense.

# noun_form - child's score on inflection of nouns by cases, range 0-10
# noun_context - also measuring inflection of nouns by cases, but in a different way: by producing a full sentence (with context) and asking parent whether child says sth like that; range 0 - 9
# nouns -  this is a summed nouns score: noun_form + noun_context to mirror the approach for verbs; however, this may not have been the best idea, as the two measures essentially ask the same question.

# adjective_adverb - child's score on the inflection of adjectives and adverbs (comparison, e.g. tall, taller, tallest), range 0-4

# vocabulary subscales:
# action words - how many verbs does the child know, range from 0 to 123
# connceting words - how many connecting words does the child know, range from 0 to 9

# for individual grammar items, see here:
# https://docs.google.com/spreadsheets/d/1HODD1g8RqkIUMzp3elGEkq_JQN5sxmW-2r2eoaweMBc/edit?gid=0#gid=0

# To run a CDI:WS in Polish (test run), go here: https://apps.multilada.pl/cdi/?form=ws-gram-p2&lang=pl&id=test100 


```

```{r include = F}
# correct data structure:
# timpoints and id should be factors
mock_n50$id <- as.factor(mock_n50$id)
mock_n50$timepoint <- as.factor(mock_n50$timepoint)

mock_n100$id <- as.factor(mock_n100$id)
mock_n100$timepoint <- as.factor(mock_n100$timepoint)
```

# Vocabulary growth

Exploring growth of vocab (overall) and grammar (overall).
T1 ~ 18 mo, T2 ~ 24 mo, T3 ~ 30 mo.
Let's try to do as much as possible on sample n50 (n100 would be much more dificult to collect).

Vocab growth seems not that linear, it could be a mock artefact but it has been reported before.
Note the wide CI error bars (my guess in real data the variability may be even greater).

```{r}
# vocab (overall)
ggplot(summarySE(mock_n50, measurevar = "vocab_score", groupvars = "timepoint"), 
       aes(x = timepoint, y = vocab_score, group = 1)) +
  geom_errorbar(aes(ymin = vocab_score - ci, ymax = vocab_score + ci), width = 0.1) +
  geom_point() +
  geom_line() 

# grammar (overall), i.e., alternatives
ggplot(summarySE(mock_n50, measurevar = "alternatives", groupvars = "timepoint"), 
       aes(x = timepoint, y = alternatives, group = 1)) +
  geom_errorbar(aes(ymin = alternatives - ci, ymax = alternatives + ci), width = 0.1) +
  geom_point() +
  geom_line() 
```
```{r}
# vocab growth - mixed linear reg
# linear for now, but vocab growth may be NON-linear

# only random intercept for child for start
m0 <- lmer(vocab_score ~ 1 + (1|id), data = mock_n50)
m1 <- lmer(vocab_score ~ timepoint + (1|id), data = mock_n50)
m2 <- lmer(vocab_score ~ timepoint + alternatives + (1|id), data = mock_n50)

anova(m0, m1, m2)
AIC(m0, m1, m2)
BIC(m0, m1, m2)

summary(m2)
# timepoints effect - yes - vocab increases between T1 and T3 (but not much between T1 and T2) - note non-linearity visible in plot above
# grammar effect - yes - quite strong (t > 4)
# random effects - yes - substantial variability between kids
# moderate correlations between T2 and T3

```

```{r}
# adding random slope for age (not possible for timepoint)
# so we include random intercept for child AND random slope for age
m0 <- lmer(vocab_score ~ 1 + (age|id), data = mock_n50)
m1 <- lmer(vocab_score ~ age + (age | id), data = mock_n50) # failed to converge
m2 <- lmer(vocab_score ~ age + alternatives + (age | id), data = mock_n50) # failed to converge

# center age
# i.e., intercept will correspond to the mean age, instead of 0 (outside the observed range), which could help the optimizer
mock_n50 <- mock_n50 %>% mutate(age_c = age - mean(age, na.rm = TRUE))
# refit
m0 <- lmer(vocab_score ~ 1 + (age_c|id), data = mock_n50)
m1 <- lmer(vocab_score ~ age_c + (age_c | id), data = mock_n50) 
m2 <- lmer(vocab_score ~ age_c + alternatives + (age_c | id), data = mock_n50) # failed to converge

# removing the correlation between intercept and slope?
# if we assume the intercepts and slopes are correlated, we presuppose that the higher the initial skill, the steeper the growth 
# which is sensible in the developmental context
# by default, lme4 estimates that correlation
m0 <- lmer(vocab_score ~ 1 + (age_c||id), data = mock_n50)
m1 <- lmer(vocab_score ~ age_c + (age_c || id), data = mock_n50) 
m2 <- lmer(vocab_score ~ age_c + alternatives + (age_c || id), data = mock_n50)

anova(m0, m1, m2)
AIC(m0, m1, m2)
summary(m2)
```

# Grammar growth

```{r}
# grammar growth - mixed linear reg
# only random intercept for child for start
m0 <- lmer(alternatives ~ 1 + (1|id), data = mock_n50)
m1 <- lmer(alternatives ~ timepoint + (1|id), data = mock_n50)
m2 <- lmer(alternatives ~ timepoint + vocab_score + (1|id), data = mock_n50)

anova(m0, m1, m2)
AIC(m0, m1, m2)
BIC(m0, m1, m2)

summary(m2)

# large effect of timepoint
# small effect of vocab
```

```{r}
# adding random slope for age (not possible for timepoint)
# so we include random intercept for child AND random slope for age
m0 <- lmer(alternatives ~ 1 + (age|id), data = mock_n50)
m1 <- lmer(alternatives ~ age + (age | id), data = mock_n50) # failed to converge
m2 <- lmer(alternatives ~ age + vocab_score + (age | id), data = mock_n50) # failed to converge

# refit with centered age
m0 <- lmer(alternatives ~ 1 + (age_c|id), data = mock_n50)
m1 <- lmer(alternatives ~ age_c + (age_c | id), data = mock_n50) 
m2 <- lmer(alternatives ~ age_c + vocab_score + (age_c | id), data = mock_n50) # boundary (singular) fit? to check?

anova(m0, m1, m2)
AIC(m0, m1, m2)
summary(m2)
```

